name: test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: test
        run: |
          docker info
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:slim bash -c 'ls -la /var/run/docker.sock'
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:slim docker ps

  macos:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:

      - uses: docker-practice/actions-setup-docker@1.0.8

      - name: test
        run: |
          docker info
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:slim bash -c 'ls -la /var/run/docker.sock'
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:slim docker ps
